### ISSUE TITLE
Enhance chart tooltips example

### ISSUE THREAD

**Issue by rmbielby** [dfe-analytical-services/shiny-template#34]
Tooltips have data-ey names eg area_name and aren’t formatted nicely. Could do with an improved demo of proper tooltip formatting.

**Comment by cjrace** [comment]
Currently it looks like this - I think this is improved to what you were thinking @rmbielby?

![image](https://github.com/user-attachments/assets/85bf23d4-18fb-44bb-8af5-8dc2b204c81c)
